[package]
name = "ifilter-disable"
version = "0.1.0"
edition = "2024"

[dependencies]
sysinfo = "0.37.2"
tokio = { version = "1", features = ["full"] }
windows-sys = { version = "0.61.2", features = ["Win32_System_Console", "Win32_UI_WindowsAndMessaging"] }
